### ISSUE TITLE
Mixed use of interfaces

### ISSUE THREAD

**Issue by pattacini** [paloskar/makeitrollicub#3]
[Looking down](https://github.com/paloskar/makeitrollicub/blob/master/src/main.cpp#L127) is performed by means of the motor interface, while [homing](https://github.com/paloskar/makeitrollicub/blob/master/src/main.cpp#L159) is done through the gaze interface. Why?

**Comment by paloskar** [comment]
I wanted the robot to look down by a specific angle and not to look down at a certain point. Then I realized that the gaze controller also allows this, but I already implemented it using the motor interface. On the positive side, at least I figured out how to use both of these interfaces in parallel.

**Comment by pattacini** [comment]
Got it.
